gitdb/base.py, gitdb/exc.py, gitdb/stream.py, gitdb/util.py
as a token of appreciation while I was sneaking through the code ;)
=> minor spell fixes + empty line unification + comparison for python 2.6

gitdb/_delta_apply.c
Remove duplicate `const` to stop the warning: "duplicate 'const' declaration specifier"
=> Remove duplicate `const`

setup.cfg
because you need to build manylinux1/mac/windows wheels instead
=> Do not support universal wheels

.appveyor.yml, README.rst, gitdb/test/performance/test_pack.py, gitdb/test/performance/test_pack_streaming.py, gitdb/test/performance/test_stream.py, gitdb/test/test_pack.py
- 3 errors remain in all python versions (py27, py34, py35, conda35).
- One set of errors fixed: div-by-zero on elapsed times - Appveyor must be quick.
=> Enable Appveyor CI for Windows

gitdb/pack.py, gitdb/test/db/test_pack.py, gitdb/test/performance/test_stream.py, gitdb/test/test_pack.py, gitdb/util.py
Fix for https://github.com/gitpython-developers/gitdb/issues/37.
All tests run also on windows now.
=> Windows fixes for leaking file handles #37

gitdb/db/loose.py
Our user was experiencing issue [1] when using a git repository on NTFS mount
running on Linux. The current check checks if we are running on Windows, but
it should really check if we are on NTFS. And since checking fs type is not
that trivial and not efficient, it is simpler and better to just always apply
NTFS-specific logic, since it works on other filesystems as well.
[1] https://github.com/iterative/dvc/issues/1880#issuecomment-483253764
=> loose: rename only if needed

gitdb/pack.py, gitdb/test/lib.py
The array methods fromstring/tostring have been deprecated since Python 3.2. Python 3.9 removes them completely.
This was discovered when trying to build gitdb package for Fedora 33.
https://bugzilla.redhat.com/show_bug.cgi?id=1788660
=> Fix deprecated calls for Python 3.9

gitdb/db/loose.py, gitdb/db/pack.py, gitdb/fun.py, gitdb/pack.py, gitdb/stream.py, gitdb/test/db/lib.py, gitdb/test/lib.py, gitdb/test/performance/test_pack.py, gitdb/test/test_pack.py, gitdb/utils/compat.py, gitdb/utils/encoding.py
This PR removes and replaces Python 2 compatibility shims, since Python 2 support was dropped with https://github.com/gitpython-developers/gitdb/commit/c880f6b0550770eee559091d6276a2e2b097a83a in 3.0.0:
- Remove `compat.memoryview` and `compat.PY3`
- Remove and replace `compat.buffer` and `compat.to_bytes`
- Remove and replace `compat.izip` with `zip`, `compat.MAXSIZE` with `sys.maxsize`, `compat.xrange` with `range`
- Remove and replace `encoding.string_types` and `encoding.text_type` with `str`
- Remove and replace `izip` in `TestPack`
=> Remove Python 2 compatibility shims

setup.cfg
As for the setup.cfg universal setting, this is actually an issue with the main gitdb package on the master branch rather than with the gitdb2 mirror package. The gitdb package has dropped support for Python 2, so it should be a Pure Python Wheel rather than a Universal Wheel
=> Remove setup.cfg to have a pure python wheel 

gitdb/db/loose.py
I recently went over [Matplotlib](https://github.com/matplotlib/matplotlib/pull/16706), [Pandas](https://github.com/pandas-dev/pandas/pull/32322) and [NumPy](https://github.com/numpy/numpy/pull/15731), fixing a small mistake in the way that Python 3's exception chaining is used. If you're interested, I can do it here too. I've done it on just one file right now. 
The mistake is this: In some parts of the code, an exception is being caught and replaced with a more user-friendly error. In these cases the syntax `raise new_error from old_error` needs to be used.
Python 3's exception chaining means it shows not only the traceback of the current exception, but that of the original exception (and possibly more.) This is regardless of `raise from`. The usage of `raise from` tells Python to put a …
=> Fix exception causes in loose.py

gitdb/test/db/lib.py, gitdb/test/db/test_git.py, gitdb/test/db/test_loose.py, gitdb/test/db/test_pack.py, gitdb/test/test_pack.py, gitdb/test/test_stream.py, gitdb/test/test_util.py
`failUnlessRaises` is deprecated and should be replaced with `assertRaises`:
* https://docs.python.org/3/library/unittest.html#deprecated-aliases
=> Replace deprecated unittest aliases

doc/source/conf.py, gitdb/db/base.py, gitdb/db/mem.py
Fixes https://github.com/gitpython-developers/gitdb/issues/71.
Two things:
* There is no `.static` dir in use, comment it out
* Docstrings usually need a new line between a summary and the params/return: https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html
```console
$ python3 setup.py build_sphinx -b man
running build_sphinx
Running Sphinx v4.0.2
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: 0 added, 0 changed, 0 removed
looking for now-outdated files... none found
writing... gitdb.1 { intro tutorial api algorithm changes } done
build succeeded.
The manual pages are in build/sphinx/man.
```
=> Fix Sphinx warnings

.github/workflows/pythonpackage.yml, gitdb/db/mem.py, gitdb/stream.py, setup.py
* Declare support for and test on Python 3.7-3.9.
* Remove some old Python 2 code.
=> Support Python 3.7-3.9

.github/workflows/pythonpackage.yml, Makefile, README.rst, gitdb.pro.user, gitdb/test/db/test_pack.py, gitdb/test/lib.py, gitdb/test/test_pack.py
This is not a full rewrite to pytest style tests, it just changes the minimum to allow pytest to run the existing tests.
Resolves #72
=> Switch from nose to pytest

.gitmodules
Github.com is currenly redirecting the smmap url:
https://github.com/Byron/smmap.git
to:
https://github.com/gitpython-developers/smmap
For correctness we update to the url directly
=> .gitmodules: update smmap url

.gitignore, gitdb/__init__.py
In `__init__.py` there is a loop that invokes `__import__` here: https://github.com/gitpython-developers/gitdb/blob/3415e08bd9590d489f1071815863bfdde3083fb3/gitdb/__init__.py#L13
Since the loop only has one item this PR convert refactors it to use the standard `import`.
Some tooling only works with modules to be imported via `import` as the packages names are resolve-able without executing code, which `__import__` prevents.
If it is desired to have `smmap` added into `globals()` of `__init__.py`; I can remove the `del smmap` line. Right now it is there because `__import__`, which `import` is replacing, does *not* add `smmap` to `globals()`
=> Prefer `import` to `__import__`

.github/workflows/pythonpackage.yml, setup.py
The [second and final Python 3.12 release candidate](https://discuss.python.org/t/python-3-12-0rc2-final-release-candidate-released/33105/5?u=hugovk) is out! :rocket:
> ## Call to action
> 
> We strongly encourage maintainers of third-party Python projects to prepare their projects for 3.12 compatibilities during this phase, and where necessary publish Python 3.12 wheels on PyPI to be ready for the final release of 3.12.0.
See also https://dev.to/hugovk/help-test-python-312-beta-1508/
---
Python 3.7 is EOL and no longer receiving security updates (or any updates) from the core Python team.
| version |  released  |    eol     |
|:--------|:----------:|:----------:|
| 3.11    | 2022-10-24 | 2027-10-24 |
| 3.10    | 2021-10-04 | 2026-10-04 |
| 3.9     | 2020-10-05 | 2025-10-05 |
| 3.8     | …
=> Add support for Python 3.12 and drop EOL 3.7

.github/dependabot.yml
This enables Dependabot version updates for GitHub Actions only (not Python dependencies), using the exact same configuration as [in GitPython](https://github.com/gitpython-developers/GitPython/blob/main/.github/dependabot.yml).
Since this repository is less active than the GitPython repository, I considered changing the `dependabot.yml` file to check for updates `monthly` rather than `weekly`. But I did not do so, because the GitHub Actions used in this repository's workflow are requested using major versions, and automatically use the latest minor (and, where applicable, patch) version in that major version automatically. As a result, Dependabot only needs to offer updates when a new major version comes out, which is a fairly infrequent event. So it is unlikely that this would ever …
=> Enable Dependabot version updates for Actions

.github/workflows/pythonpackage.yml
This changes the CI workflow to install the project itself to get its dependency, rather than installing the dependency from `requirements.txt`. This is the more important thing to test, because it verifies that the project is installable and effectively declares the dependencies it needs.
=> Test installing project on CI

gitdb/db/loose.py
Fixes #85
This replaces the conditional call to `os.mkdir` that raises an unintended `FileExistsError` if the directory is created between the check and the `os.mkdir` call, using a single `os.makedirs` call instead, with `exist_ok=True`.
This way, we attempt creation in a way that produces no error if the directory is already present, while still raising `FileExistsError` if a non-directory filesystem entry (such as a regular file) is present where we want the directory to be. This is the advantage of this approach over the approach of swallowing `FileExistError` as suggested in #85.
**Note, however, that `os.makedirs` behaves like `mkdir -p`**: it attempts to create parent directories (and their parents, etc.) if they do not already exist. So it should only be used if that is acceptable …
=> Fix mkdir race condition in LooseObjectDB.store

.github/workflows/pythonpackage.yml
It appears the intent of specifying a `fetch-depth` of `1000` is that 1000 is greater enough than the current number of commits in the repository that it will fetch the whole branch history, now and for some time into the future.
Assuming that is the case, I recommend [doing a full fetch instead](https://github.com/actions/checkout?tab=readme-ov-file#Fetch-all-history-for-all-tags-and-branches), which this PR changes it to do. Setting the `fetch-depth` to a positive value fetches that many commits back (and the default value is 1), but setting it to 0 fetches all commits, as in a normal deep (full) fetch.
=> Use actions/checkout feature to fetch all commits

.github/workflows/pythonpackage.yml, setup.py
This brings back Python 3.7 support (allowing it to be installed on 3.7, and testing on 3.7 on CI), even though 3.7 is end-of-life. The reason is that support for 3.7 is not being dropped by GitPython yet, and there is value in keeping the version ranges supported by GitPython and gitdb consistent. This is noted in review comments on https://github.com/gitpython-developers/GitPython/pull/1654.
This reverts commit 875acb45cd8e9353c1911717bd2cd05b3e40ed05.
=> Revert "Drop support for EOL Python 3.7"

.github/workflows/pythonpackage.yml
Python 3.12.0 stable has been released, as well as now being [available via setup-python](https://github.com/actions/python-versions/blob/main/versions-manifest.json), and these tests have been passing with the release candidate. So this changes the CI test workflow to no longer treat it as experimental. This has two effects:
- `continue-on-error` is no longer set to true for 3.12, so 3.12 is no longer special-cased to refrain from cancelling other test jobs when its test job fails. This is the more significant effect.
- 3.12 can longer be selected as a prerelease. This is the only effect in GitPython, but the less significant of the two effects here and in smmap (GitPython sets `fail-fast` to `false`, so one job failing never automatically cancels another job).
With respect to the …
=> No longer treat 3.12 as experimental on CI

.github/dependabot.yml
This makes Dependabot open version update PRs for submodules (which here is just smmap), as well as GitHub Actions. This is like https://github.com/gitpython-developers/GitPython/pull/1702.
=> Have Dependabot update smmap submodule dependency

gitdb/__init__.py
This removes the logic that appended the git submodule directory for `smmap` to `sys.path` under most circumstances when the version of `gitdb` was not from PyPI. Now `gitdb` does not modify `sys.path`.
See [GitPython#1717](https://github.com/gitpython-developers/GitPython/issues/1717) and [GitPython#1720](https://github.com/gitpython-developers/GitPython/pull/1720) for context. This change is roughly equivalent to the change to GitPython, though as noted the behavior being eliminated is subtly different here and there.
Please note that this does *not* make any documentation changes (and the changes in #103 are not related to this).
=> Never add a vendored smmap directory to sys.path

README.rst
Changes worth mentioning:
- Format commands as code blocks instead of blockquotes. (This is particularly useful for the submodule update step, whose lines were inadvertently concatenated, but it also improves appearance overall.)
- Mention `smmap` as a requirement. (But also that it doesn't need to be separately installed.)
- Mention that `gitdb-speedups` is not currently maintained.
- No longer say `gitdb` has source code in gitorious. (Since that site no longer exists.)
- Call GitPython "GitPython" rather than "git-python".
- Replace the old git-python Google Groups link with a link to the Discussions page on the GitHub repository for GitPython. (This seems like the closest currently available resource.)
Please note that this does *not* make any changes related to #102.
=> Revise and update the readme

.github/dependabot.yml
This changes it from monthly to weekly. See #99 for general context and [GitPython#1702 (comment)](https://github.com/gitpython-developers/GitPython/pull/1702#issuecomment-1761182333) for where this was requested as an eventual change.
With recent and proposed changes to gitdb, it seems to make sense to propose this now. I've done this in its own PR so this change can be applied at whatever point is most convenient, without being directly tied to any of the other proposed changes.
=> Set Dependabot submodule update cadence to weekly

gitdb/test/test_base.py
fix #101
Added the missing assert pointed out in the related issue, plus another similar one.
=> Add missing asserts in test_base.py

gitdb/db/loose.py
This PR refactors the `LooseObjectDB` class in gitdb/db/loose.py to utilize `contextlib.suppress` for handling `KeyError` exceptions, replacing the previous try-except block.
This change improves code readability and aligns with best practices for exception handling in Python.
=> Use contextlib.suppress instead of except: pass

.github/workflows/pythonpackage.yml, setup.py
Python 3.13 is out, so it'd be nice if the next release of gitdb to PyPI included it in its metadata.
Though you might wanna wait for https://github.com/gitpython-developers/GitPython/pull/1955?
https://pyreadiness.org/3.13/
=> Add support for Python 3.13

gitdb/db/loose.py
There is a really flaky and hard to debug bug when using `gitdb` at least on MacOS (M-Processor) using Docker (`docker.io/python:3.13` image).
I have only been able to reproduce this error within `pytest` on my laptop (Apple M4 laptop).
I completely randomly get:
```python
repo = Repo(........)  # Repo Created using `GitPython`
[...]
repo.index.add("*")
~~~~~~~~~~~~~~^^^^^
File "/usr/local/lib/python3.13/site-packages/git/index/base.py", line 885, in add
entries_added.extend(self._entries_for_paths(paths, path_rewriter, fprogress, entries))
~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.13/site-packages/git/util.py", line 176, in wrapper
return func(self, *args, **kwargs)
File "/usr/local/lib/python3.13/site-packages/git/index/util.py", line …
```
=> Potential Race Condition Fix - OS Rename & Chmod - PermissionError

gitdb/db/loose.py
The sequence of backoff wait times used in `gitdb.db.loose` is quadratic rather than exponential, as discussed in https://github.com/gitpython-developers/gitdb/pull/115#discussion_r1903215598.
This corrects the variable name by making it more general, and the comment by having it explicitly describe the backoff as quadratic.
This is conceptually related to GitoxideLabs/gitoxide#1815, but this is a non-breaking change, as no interfaces are affected: only a local variable and comment.
=> Improve description of backoff sequence in `db.loose`

.github/workflows/pythonpackage.yml
This change is analogous to gitpython-developers/GitPython#2033.
See also gitpython-developers/smmap#60.
=> Specify explicit `contents: read` workflow permissions
